# -*- coding: utf-8 -*-
"""pattern sense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3otD6wjnUdfpSza_lx0n35KeFrR4trg
"""

import os

print(os.path.exists("/content/archive (1).zip"))
print(os.path.getsize("/content/archive (1).zip"))

!unzip -l "/content/archive (1).zip"

import zipfile
import os

# Path to your dataset ZIP
zip_file = "/content/archive (1).zip"

# Define the extraction directory
extraction_dir = "/content/dataset"

# Create the extraction directory if it doesn't exist
os.makedirs(extraction_dir, exist_ok=True)

# Extract dataset
with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall(extraction_dir)

print(f"Dataset Extracted Successfully to {extraction_dir}!")

# Display folder structure of the extracted dataset
print("Extracted Dataset Structure:")
for root, dirs, files in os.walk("/content/dataset"):
    print(root)

# Import libraries if not already imported
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Define paths and parameters
DATA_DIR = '/content/dataset/data_pattern'
IMAGE_SIZE = (128, 128)
BATCH_SIZE = 32

# Data Augmentation and Preprocessing for Training Data
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest',
    validation_split=0.2 # Using 20% of data for validation
)

# Preprocessing for Validation Data (only rescaling)
# Validation data should not be augmented, only rescaled
validation_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Create Training and Validation Generators
train_generator = train_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    seed=42
)

validation_generator = validation_datagen.flow_from_directory(
    DATA_DIR,
    target_size=IMAGE_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation',
    seed=42
)

print(f"Found {train_generator.samples} training images belonging to {train_generator.num_classes} classes.")
print(f"Found {validation_generator.samples} validation images belonging to {validation_generator.num_classes} classes.")

# Install libraries
!pip -q install tensorflow

# Import libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Path to extracted dataset
dataset_path = "/content/archive (1).zip"

print("Dataset Path:", dataset_path)

# Display folder structure
for root, dirs, files in os.walk(dataset_path):
    print(root)

import os
for root, dirs, files in os.walk("/content/dataset"):
    print(root)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_data = train_datagen.flow_from_directory(
    "/content/dataset/data_pattern",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="training",
    shuffle=True
)

val_data = train_datagen.flow_from_directory(
    "/content/dataset/data_pattern",
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    subset="validation",
    shuffle=True
)

base_model = tf.keras.applications.MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

base_model.trainable = False

model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(train_data.num_classes, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

print("Classes:", train_data.class_indices)
model.summary()

history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=10
)

# Plot Accuracy
plt.figure(figsize=(8,5))
plt.plot(history.history["accuracy"], label="Train Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# Save Model
model.save("fabric_classifier.h5")

# Save Labels
labels = list(train_data.class_indices.keys())

with open("labels.txt", "w") as f:
    for label in labels:
        f.write(label + "\n")

print("Model Saved Successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import tensorflow as tf
# import numpy as np
# from PIL import Image
# 
# model = tf.keras.models.load_model("fabric_classifier.h5")
# 
# with open("labels.txt") as f:
#     labels = f.read().splitlines()
# 
# st.set_page_config(page_title="PatternSense")
# 
# st.title("👗 PatternSense")
# st.subheader("Fabrics Classification using Deep Learning")
# 
# uploaded = st.file_uploader(
#     "Upload a Image of fabric",
#     type=["jpg","jpeg","png"]
# )
# 
# if uploaded:
# 
#     image = Image.open(uploaded).convert("RGB")
# 
#     st.image(image, caption="Uploaded Image", use_container_width=True)
# 
#     img = image.resize((224,224))
#     img = np.array(img)/255.0
#     img = np.expand_dims(img,0)
# 
#     prediction = model.predict(img)
# 
#     index = np.argmax(prediction)
# 
#     confidence = np.max(prediction)*100
# 
#     st.success(f"Predicted Pattern: {labels[index]}")
#     st.write(f"Confidence: {confidence:.2f}%")

!pip -q install streamlit pyngrok

from pyngrok import ngrok
import threading
import os

ngrok.set_auth_token("YOUR API KEY")  # Replace with your ngrok token

def run():
    os.system("streamlit run app.py --server.port 8501")

threading.Thread(target=run).start()

public_url = ngrok.connect(8501)

print("Open this URL in your browser:")
print(public_url)